package transaction;

public enum TransactionDetail {
    TRANSFER,
    CREATE_DEPOSIT,
    LIQUIDATE_DEPOSIT,
    INTEREST_FROM_DEPOSIT,
    WITHDRAW_MONEY_FROM_ATM,
    WITHDRAW_FEE_FROM_ATM,
    INTERNAL_PAYMENT_FEE,
    EXTERNAL_PAYMENT_FEE,
    PAYMENT,
    LOAN_GRANTING,
    PAYMENT_FOR_LOAN,
    INTEREST_FOR_LOAN,
    CURRENCY_EXCHAGE_PAID,
    CURRENCY_EXCHANGE_RECEIVED,
    OTHER_TRANSACTION
}
